/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for creating a TextToCypher client */
export interface ClientOptions {
  /** The AI model to use (e.g., "gpt-4o-mini", "anthropic:claude-3") */
  model: string
  /** API key for the AI service */
  apiKey: string
  /** FalkorDB connection string (e.g., "falkor://localhost:6379") */
  falkordbConnection: string
}
/** A chat message in the conversation */
export interface Message {
  /** Role of the message sender: "user", "assistant", or "system" */
  role: string
  /** Content of the message */
  content: string
}
/** Response from text-to-cypher operations */
export interface TextToCypherResponse {
  /** Status of the operation: "success" or "error" */
  status: string
  /** The discovered graph schema (JSON string) */
  schema?: string
  /** The generated Cypher query */
  cypherQuery?: string
  /** The result from executing the Cypher query */
  cypherResult?: string
  /** Natural language answer generated from the results */
  answer?: string
  /** Error message if status is "error" */
  error?: string
}
/**
 * Node.js wrapper for the text-to-cypher Rust library
 *
 * This class provides methods to convert natural language text to Cypher queries
 * and execute them against a FalkorDB instance.
 *
 * # Example
 *
 * ```javascript
 * const { TextToCypher } = require('@falkordb/text-to-cypher-node');
 *
 * const client = new TextToCypher({
 *   model: 'gpt-4o-mini',
 *   apiKey: 'your-api-key',
 *   falkordbConnection: 'falkor://localhost:6379'
 * });
 *
 * const response = await client.textToCypher('movies', 'Find all actors');
 * console.log(response.answer);
 * ```
 */
export declare class TextToCypher {
  /**
   * Creates a new TextToCypher client
   *
   * # Arguments
   *
   * * `options` - Client configuration including model, API key, and FalkorDB connection
   *
   * # Example
   *
   * ```javascript
   * const client = new TextToCypher({
   *   model: 'gpt-4o-mini',
   *   apiKey: 'your-api-key',
   *   falkordbConnection: 'falkor://localhost:6379'
   * });
   * ```
   */
  constructor(options: ClientOptions)
  /**
   * Converts natural language text to Cypher and executes the query
   *
   * This method:
   * 1. Discovers the graph schema
   * 2. Generates a Cypher query using AI
   * 3. Executes the query
   * 4. Generates a natural language answer
   *
   * # Arguments
   *
   * * `graph_name` - Name of the graph to query
   * * `question` - Natural language question or request
   *
   * # Returns
   *
   * A promise that resolves to a TextToCypherResponse containing the query, result, and answer
   *
   * # Example
   *
   * ```javascript
   * const response = await client.textToCypher(
   *   'movies',
   *   'Find all actors who appeared in movies released after 2020'
   * );
   * console.log('Query:', response.cypherQuery);
   * console.log('Answer:', response.answer);
   * ```
   */
  textToCypher(graphName: string, question: string): Promise<TextToCypherResponse>
  /**
   * Converts natural language text to Cypher and executes the query with multiple messages
   *
   * This method allows for conversation history by accepting multiple messages.
   *
   * # Arguments
   *
   * * `graph_name` - Name of the graph to query
   * * `messages` - Array of conversation messages
   *
   * # Returns
   *
   * A promise that resolves to a TextToCypherResponse
   *
   * # Example
   *
   * ```javascript
   * const response = await client.textToCypherWithMessages('movies', [
   *   { role: 'user', content: 'Show me actors' },
   *   { role: 'assistant', content: 'Here are the actors...' },
   *   { role: 'user', content: 'Filter those who acted after 2020' }
   * ]);
   * ```
   */
  textToCypherWithMessages(graphName: string, messages: Array<Message>): Promise<TextToCypherResponse>
  /**
   * Generates a Cypher query without executing it
   *
   * Use this when you only want to generate the query for inspection or manual execution.
   *
   * # Arguments
   *
   * * `graph_name` - Name of the graph to generate query for
   * * `question` - Natural language question or request
   *
   * # Returns
   *
   * A promise that resolves to a TextToCypherResponse with only the schema and query
   *
   * # Example
   *
   * ```javascript
   * const response = await client.cypherOnly('movies', 'Find all actors');
   * console.log('Generated query:', response.cypherQuery);
   * // You can now review, modify, or execute the query yourself
   * ```
   */
  cypherOnly(graphName: string, question: string): Promise<TextToCypherResponse>
  /**
   * Discovers and returns the schema of a graph
   *
   * # Arguments
   *
   * * `graph_name` - Name of the graph to discover schema for
   *
   * # Returns
   *
   * A promise that resolves to a JSON string representing the graph schema
   *
   * # Example
   *
   * ```javascript
   * const schema = await client.discoverSchema('movies');
   * console.log('Schema:', JSON.parse(schema));
   * ```
   */
  discoverSchema(graphName: string): Promise<string>
}
